services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_net
    depends_on:
      - contadorstatefull01
      - contadorstatefull02
  
  contadorstatefull01:
    image: dellabeneta/contadorstatefull:v1
    build:
      context: ./contadorstatefull
      dockerfile: Dockerfile
    networks:
      - my_net
    
  contadorstatefull02:
    image: dellabeneta/contadorstatefull:v1
    depends_on:
      - contadorstatefull01
    networks:
      - my_net

  contadorstateless01:
    image: dellabeneta/contadorstateless:v1
    build:
      context: ./contadorstateless
      dockerfile: Dockerfile
    networks:
      - my_net
    environment:
      REDIS_HOST: redis
    
  contadorstateless02:
    image: dellabeneta/contadorstateless:v1
    depends_on:
      - contadorstateless01
    networks:
      - my_net
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:latest
    networks:
      - my_net

networks:
  my_net:
    driver: bridge